import { Geist, Geist_Mono , Gulzar } from "next/font/google";
import FacebookSDK from "@/components/FacebookSDK";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import WhatsAppChat from "@/components/WhatsAppChat/WhatsAppChat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const gulzar = Gulzar({
  subsets: ["arabic"],
  weight: "400",
  variable: "--font-gulzar",
});


export const metadata = {
  title: "Ahmad-ElectroGas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${gulzar.variable}  h-full antialiased`}
      
    >
      <body className={`${gulzar.variable} min-h-full flex flex-col`}>
        <Navbar/>
        <FacebookSDK/>
        <WhatsAppChat/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
